# Generated by Django 6.1 on 2026-09-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnKeeper_app', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('picture', models.FileField(upload_to='resorts/pictures/')),
                ('pricing', models.CharField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort', to='InnKeeper_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('lawn', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='InnKeeper_app.resorts')),
            ],
        ),
    ]
