# Generated by Django 6.1 on 2026-09-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnKeeper_app', '0003_resorts_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilities',
            old_name='user',
            new_name='resort',
        ),
    ]
