# Generated by Django 6.1 on 2026-09-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnKeeper_app', '0004_rename_user_facilities_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='resorts',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resorts',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
