# Generated by Django 6.1 on 2026-09-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnKeeper_app', '0005_resorts_address_resorts_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('facilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='InnKeeper_app.facilities')),
            ],
        ),
    ]
