# Generated by Django 6.1 on 2026-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnKeeper_app', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
