# Generated by Django 6.1 on 2026-09-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnKeeper_app', '0008_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_data',
            field=models.DateField(auto_now=True),
        ),
    ]
